### ISSUE TITLE
change pointless plain text converters to be incorperated into the sequelize call

### ISSUE THREAD

**Issue by brandonnorsworthy** [brandonnorsworthy/meet-up#76]
![image](https://user-images.githubusercontent.com/25205589/128595824-58719b82-089c-4c34-8927-2cb7c499d586.png)
![image](https://user-images.githubusercontent.com/25205589/128595825-9eacf82f-0f0e-43ac-863f-04725b2c806c.png)

**Comment by Cuillerethedj** [comment]
updated but having issues with mySQL working on it now
